[package]
name = "extract-parquet-to-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "^0.25.5"
math_images_processor = "^0.1.1"
parquet = { version = "^53.3.0", features = ["arrow", "json"] }
serde_json = "^1.0.133"
